dist: trusty
group: stable
sudo: required

env:
  - SCALANATIVE_GC=boehm

language: scala
matrix:
  include:
    - jdk: openjdk8
      scala: 2.11.12
    - jdk: openjdk8
      scala: 2.12.8
#    - jdk: openjdk11

before_install:
  - bash scripts/travis_setup.sh

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"
 - unset _JAVA_OPTIONS

script: sbt ++$TRAVIS_SCALA_VERSION scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
